CommitteeAdministration/CommitteeAdministration/ViewModels/SubCriterionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using CommitteeManagement.Model;

namespace CommitteeAdministration.ViewModels
{
    public class SubCriterionViewModel
    {
    }

    public class CreateSubCriterionViewModel
    {
        [Required(ErrorMessage = "لطفا زیر معیار مورد نظر را وارد کنید"), Display(Name = "عنوان زیر معیار")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "لطفا ضریب را وارد نمایید")]
        [Range(0, 1, ErrorMessage = "ضریب را در بازه 0 و 1 وارد کنید"), Display(Name = "ضریب زیر معیار")]
        public double? Coefficient { get; set; }

        public int? CommitteeId { get; set; }
        public virtual Committee Committee { get; set; }

        public int? CriterionId { get; set; }
        public virtual Criterion Criterion { get; set; }
    }
}

CommitteeAdministration/CommitteeAdministration/Controllers/SubCriterionsController.cs
using System;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using CommitteeAdministration.Helper;
using CommitteeAdministration.ViewModels;
using CommitteeManagement.Model;
using CommitteeManagement.Repository;
using Microsoft.Practices.Unity;

namespace CommitteeAdministration.Controllers
{
    /// <summary>
    /// sub criterion cotroller
    /// </summary>
    /// <seealso cref="System.Web.Mvc.Controller" />
   // [Authorize(Roles = "SuperAdmin,Manager")]
    public class SubCriterionsController : Controller
    {
        private readonly IMainContainer _mainContainer = ModelContainer.Instance.Resolve<IMainContainer>();

        // GET: SubCriterions        
        /// <summary>
        /// list all
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> Index()
        {
            var subCriterions = _mainContainer.SubCriterionRepository.AllIncluding(subCriterion => subCriterion.Criterion);
            return View(await subCriterions.ToListAsync());
        }
        private User GetCurrentUser()
        {
            return _mainContainer.UserRepository.FirstOrDefault(user => user.UserName == HttpContext.User.Identity.Name);
        }
        // GET: SubCriterions/Details/5        
        /// <summary>
        /// Detailses the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var subCriterion = await _mainContainer.SubCriterionRepository.FirstOrDefaultAsync(subCriterions=>subCriterions.Id==id);
            if (subCriterion == null)
            {
                return HttpNotFound();
            }
            return View(subCriterion);
        }
        /// <summary>
        /// Creates the sub criterion as a partial view.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult CreateSubCriterionPartial(int criterionId)
        {
            var criterion = _mainContainer.CriterionRepository.FirstOrDefault(criterionT => criterionT.Id == criterionId);
            var model = new CreateSubCriterionViewModel
            {
                Committee = criterion.Committee,
                Criterion = criterion,
            };
            return PartialView(model);
        }
        /// <summary>
        /// Creates the sub criterion as a partial view.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateSubCriterionPartial(CreateSubCriterionViewModel subCriterion)
        {
            if (ModelState.IsValid)
            {
                if (subCriterion.Coefficient == null)
                    return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest));
                var subCriterionT = new SubCriterion
                {
                    Committee = subCriterion.Committee,
                    CommitteeId = subCriterion.Committee.Id,
                    Criterion = subCriterion.Criterion,
                    CriterionId = subCriterion.Criterion.Id,
                    Coefficient = subCriterion.Coefficient.Value,
                    Subject = subCriterion.Subject
                };

                _mainContainer.SubCriterionRepository.Add(subCriterionT);
                SubCriterionModification subCriterionModification = new SubCriterionModification()
                {
                    Add = true,
                    SubCriterion = subCriterionT,
                    Time = DateTime.Now,
                    User = GetCurrentUser(),
                    
                };
                _mainContainer.SubCriterionModificationRepository.Add(subCriterionModification);
                await _mainContainer.SaveChangesAsync();
                return Json(new HttpStatusCodeResult(HttpStatusCode.OK));//RedirectToAction("ViewAll","CriteriaScInd");
            }

            return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest));
        }
        [HttpGet]
        public ActionResult EditSubCriterionPartial(int subCriterionId)
        {
            var subCriterion =
                _mainContainer.SubCriterionRepository.FirstOrDefault(subCriterionT => subCriterionT.Id == subCriterionId);
            return PartialView(subCriterion);
        }
        [HttpPost]
        public ActionResult EditSubCriterionPartial(SubCriterion postSubCriterion)
        {
            if (ModelState.IsValid)
            {
                var subCriterion = _mainContainer.SubCriterionRepository.FirstOrDefault(subCriterionT => subCriterionT.Id == postSubCriterion.Id);
                subCriterion.Subject = postSubCriterion.Subject;
                _mainContainer.SubCriterionRepository.Attach(subCriterion);
                return Json(new HttpStatusCodeResult(HttpStatusCode.OK));
            }

            return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest));
        }
        /// <summary>
        /// Deletes the specific subcriterion in tree view of all data of committee.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> DeletePartial(int? id)
        {
            if (id == null)
            {
                return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest));
            }
            SubCriterion subCriterion = await _mainContainer.SubCriterionRepository.FirstOrDefaultAsync(subcriterionT => subcriterionT.Id == id);
            if (subCriterion == null)
            {
                return Json(new HttpStatusCodeResult(HttpStatusCode.InternalServerError));//HttpNotFound());
            }
            subCriterion.IsDeleted = true;
            _mainContainer.SubCriterionRepository.Attach(subCriterion);

            var indicators =
                _mainContainer.IndicatorRepository.Where(indicator => indicator.SubCriterion.Id == subCriterion.Id);
            
            foreach (var indicator in indicators)
            {
                indicator.IsDeleted = true;
                _mainContainer.IndicatorRepository.Attach(indicator);
            }
            
            return Json(new HttpStatusCodeResult(HttpStatusCode.OK));// View(criterion);
        }
        // GET: SubCriterions/Create        
        /// <summary>
        /// Creates this instance.
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            ViewBag.CriterionId = new SelectList(_mainContainer.CriterionRepository.All(), "Id", "Subject");
            return View();
        }

        // POST: SubCriterions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.        
        /// <summary>
        /// Creates the specified sub criterion.
        /// </summary>
        /// <param name="subCriterion">The sub criterion.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Subject,Coefficient,IsDeleted,CriterionId")] SubCriterion subCriterion)
        {
            if (ModelState.IsValid)
            {
                _mainContainer.SubCriterionRepository.Add(subCriterion);
                await _mainContainer.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CriterionId = new SelectList(_mainContainer.CriterionRepository.All(), "Id", "Subject", subCriterion.CriterionId);
            return View(subCriterion);
        }

        // GET: SubCriterions/Edit/5        
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var subCriterion = await _mainContainer.SubCriterionRepository.FirstOrDefaultAsync(subCriterions => subCriterions.Id == id);
            if (subCriterion == null)
            {
                return HttpNotFound();
            }
            ViewBag.CriterionId = new SelectList(_mainContainer.CriterionRepository.All(), "Id", "Subject", subCriterion.CriterionId);
            return View(subCriterion);
        }

        // POST: SubCriterions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.        
        /// <summary>
        /// Edits the specified sub criterion.
        /// </summary>
        /// <param name="subCriterion">The sub criterion.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Subject,Coefficient,IsDeleted,CriterionId")] SubCriterion subCriterion)
        {
            if (ModelState.IsValid)
            {
                _mainContainer.Entry(subCriterion).State = EntityState.Modified;
                await _mainContainer.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CriterionId = new SelectList(_mainContainer.CriterionRepository.All(), "Id", "Subject", subCriterion.CriterionId);
            return View(subCriterion);
        }

        // GET: SubCriterions/Delete/5        
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>

CommitteeAdministration/CommitteeAdministration/Views/SubCriterions/Create.cshtml
@model CommitteeManagement.Model.SubCriterion

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SubCriterion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coefficient, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Coefficient, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Coefficient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDeleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeleted)
                    @Html.ValidationMessageFor(model => model.IsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CriterionId, "CriterionId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CriterionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CriterionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CommitteeAdministration/CommitteeAdministration/Views/SubCriterions/CreateSubCriterionPartial.cshtml
@model CommitteeAdministration.ViewModels.CreateSubCriterionViewModel


<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<style>
    .ui-widget-header, .ui-state-default, .ui-button {
        background: #b9cd6d;
        border: 1px solid #b9cd6d;
        color: #FFFFFF;
        font-weight: bold;
    }
</style>

<script>
$(document).ready(function(){
    $("form").submit(function(e) {
        e.preventDefault();
        var dd = $("#SubCriterionSubmitForm").serialize();
        console.log(dd);
        $.ajax({
            url: "/SubCriterions/CreateSubCriterionPartial",
            type: 'post',
            dataType: 'json',
            async: false,
            data:$("#SubCriterionSubmitForm").serialize(),
            success: function(response) {
                var result = response.StatusCode;
                if (result===200) {
                    alert("افزودن زیر معیار با موفقیت انجام شد");
                    $("#SubCriterionSubmitForm").hide();
                } else {
                    alert("مشکلی در افزودن پیش آمد. مجددا تلاش کنید.");
                    $("#SubCriterionSubmitForm").hide();
                }
            },
            error: function(xhr) {

            alert("Something went wrong, please try again");
            $("#SubCriterionSubmitForm").hide();
        }

        });
        
    });
});
</script>
@using (Html.BeginForm("CreateSubCriterionPartial","SubCriterions",FormMethod.Post,new{@id="SubCriterionSubmitForm"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" dir="rtl" align="right">
       <h4>افزودن زیر معیار</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Subject, "", new {@class = "text-danger"})
            </div>
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
        </div>

        <div class="form-group">

            <div class="col-md-10">
                @Html.EditorFor(model => model.Coefficient, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Coefficient, "", new {@class = "text-danger"})
            </div>
            @Html.LabelFor(model => model.Coefficient, htmlAttributes: new {@class = "control-label col-md-2"})
        </div>
        <div style="display: none">
            @Html.EditorFor(model => model.Committee, new { htmlAttributes = new { @style = "display: none" } })
            @Html.EditorFor(model => model.Criterion, new { htmlAttributes = new { @style = "display: none" } })
        </div>
       
    </div>
}

CommitteeAdministration/CommitteeAdministration/Views/SubCriterions/Delete.cshtml
@model CommitteeManagement.Model.SubCriterion

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SubCriterion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Criterion.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Criterion.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coefficient)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coefficient)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CommitteeAdministration/CommitteeAdministration/Views/SubCriterions/Details.cshtml
@model CommitteeManagement.Model.SubCriterion

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SubCriterion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Criterion.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Criterion.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coefficient)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coefficient)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CommitteeAdministration/CommitteeAdministration/Views/SubCriterions/Edit.cshtml
@model CommitteeManagement.Model.SubCriterion

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SubCriterion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coefficient, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Coefficient, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Coefficient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDeleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeleted)
                    @Html.ValidationMessageFor(model => model.IsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CriterionId, "CriterionId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CriterionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CriterionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CommitteeAdministration/CommitteeAdministration/Views/SubCriterions/EditSubCriterionPartial.cshtml
@model CommitteeManagement.Model.SubCriterion


<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<style>
    .ui-widget-header, .ui-state-default, .ui-button {
        background: #b9cd6d;
        border: 1px solid #b9cd6d;
        color: #FFFFFF;
        font-weight: bold;
    }
</style>

@using (Html.BeginForm("EditSubCriterionPartial", "SubCriterions", FormMethod.Post, new { @id = "SubCriterionEditForm" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" align="right" dir="rtl">
        <h4>زیر معیار</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Subject, "", new {@class = "text-danger"})
            </div>
            @*@Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })*@
            @Html.Label("", "عنوان زیر معیار", htmlAttributes: new { @class = "control-label col-md-2" })
        </div>
        
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CommitteeAdministration/CommitteeAdministration/Views/SubCriterions/Index.cshtml
@model IEnumerable<CommitteeManagement.Model.SubCriterion>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Criterion.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Coefficient)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Criterion.Subject)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Subject)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Coefficient)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsDeleted)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>