CommitteeAdministration/CommitteeAdministration/Controllers/CriteriaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CommitteeAdministration.Helper;
using CommitteeAdministration.ViewModels;
using CommitteeManagement.Model;
using CommitteeManagement.Repository;
using CommitteeManagement.Repository.Data;
using Microsoft.Practices.Unity;

namespace CommitteeAdministration.Controllers
{
    /// <summary>
    /// main controller of criterion 
    /// </summary>
    /// <seealso cref="System.Web.Mvc.Controller" />
   // [Authorize(Roles = "SuperAdmin,Manager")]
    public class CriteriaController : Controller
    {
        private readonly IMainContainer _mainContainer = ModelContainer.Instance.Resolve<IMainContainer>();
        /// <summary>
        /// Possible actions on criterion. Used to Insert CriterionModification Row 
        /// </summary>
        private enum CriterionAction
        {
            Add,
            Delete,
            Edit
        }
        /// <summary>
        /// main list view of all criteria
        /// </summary>
        /// <returns></returns>
        // GET: Criteria
        public async Task<ActionResult> Index()
        {
            return View(await _mainContainer.CriterionRepository.All().Where(criterion=> !criterion.IsDeleted.Value || criterion.IsDeleted == null).ToListAsync());
        }
        ///HttpGet
        /// <summary>
        /// Creates the criterion using a partial view.
        /// used in the viewall view that shows all data of committee
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult CreateCriterionPartial(int committeeId)
        {
           
            var committee = _mainContainer.CommitteeRepository.FirstOrDefault(committeeT => committeeT.Id == committeeId);
            var model = new CreateCriterionViewModel {Committee = committee};
            return PartialView(model);
        }
        // POST: Criteria/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.        
        /// <summary>
        /// Creates the specified criterion.
        /// </summary>
        /// <param name="criterion">The criterion.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCriterionPartial(CreateCriterionViewModel criterion)
        {
            if (ModelState.IsValid)
            {
                var criterionT=new Criterion
                {
                    Coefficient = criterion.Coefficient,
                    Committee = criterion.Committee,
                    CommitteeId = criterion.Committee.Id,
                    Subject = criterion.Subject
                };

                _mainContainer.CriterionRepository.Add(criterionT);
                
                CriterionModification(criterionT, CriterionAction.Add);
                _mainContainer.SaveChangesAsync();
                return Json(new HttpStatusCodeResult(HttpStatusCode.OK));
            }

            return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest));
        }
        /// <summary>
        /// Edits the criterion in a partial view.
        /// </summary>
        /// <param name="criterionId">The criterion identifier.</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult EditCriterionPartial(int criterionId)
        {
            var criterion = _mainContainer.CriterionRepository.FirstOrDefault(criterionT => criterionT.Id == criterionId);
            return PartialView(criterion);
        }
        [HttpPost]
        public ActionResult EditCriterionPartial(Criterion postCriterion)
        {
            if (ModelState.IsValid)
            {
                var criterion = _mainContainer.CriterionRepository.FirstOrDefault(criterionT => criterionT.Id == postCriterion.Id);
                criterion.Subject = postCriterion.Subject;
                _mainContainer.CriterionRepository.Attach(criterion);
                return Json(new HttpStatusCodeResult(HttpStatusCode.OK));
            }
            
            return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest));
        }
        // GET: Criteria/Details/5        
        /// <summary>
        /// Detailses the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var criterion = await _mainContainer.CriterionRepository.FirstOrDefaultAsync(criterionT=>criterionT.Id==id && (!criterionT.IsDeleted.Value || criterionT.IsDeleted==null));
            if (criterion == null)
            {
                return HttpNotFound();
            }
            return View(criterion);
        }

        
        // GET: Criteria/Create        
        /// <summary>
        /// Creates this instance.
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }

        // POST: Criteria/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.        
        /// <summary>
        /// Creates the specified criterion.
        /// </summary>
        /// <param name="criterion">The criterion.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Subject,Coefficient,IsDeleted")] Criterion criterion)
        {
            if (ModelState.IsValid)
            {
                _mainContainer.CriterionRepository.Add(criterion);
                CriterionModification(criterion,CriterionAction.Add);
                await _mainContainer.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(criterion);
        }
        /// <summary>
        /// Criterion modification.
        /// </summary>
        /// <param name="criterion">The criterion.</param>
        /// <param name="action">The action.</param>
        private void CriterionModification(Criterion criterion,CriterionAction action)
        {
            var loginUser =
                _mainContainer.UserRepository.FirstOrDefault(user => user.UserName == HttpContext.User.Identity.Name);
            var criterionModification=new CriterionModification()
            {
                Add=action==CriterionAction.Add,Criterion = criterion,Time = DateTime.Now,
                User = loginUser,UserId = loginUser.Id,
                Delete = action==CriterionAction.Delete,
                Update = action==CriterionAction.Edit
            };
            _mainContainer.CriterionModificationRepository.Add(criterionModification);
        }
        // GET: Criteria/Edit/5        
        /// <summary>
        /// Edits the specified criterion with identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var criterion = await _mainContainer.CriterionRepository.FirstOrDefaultAsync(criterionT => criterionT.Id == id && (!criterionT.IsDeleted.Value || criterionT.IsDeleted == null));
            if (criterion == null)
            {
                return HttpNotFound();
            }
            return View(criterion);
        }

        // POST: Criteria/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.        
        /// <summary>
        /// Edits the specified criterion.
        /// </summary>
        /// <param name="criterion">The criterion.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Subject,Coefficient,IsDeleted")] Criterion criterion)
        {
            if (ModelState.IsValid)
            {

                _mainContainer.Entry(criterion).State = EntityState.Modified;
                CriterionModification(criterion, CriterionAction.Edit);
                await _mainContainer.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(criterion);
        }

        // GET: Criteria/Delete/5        
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> DeletePartial(int? id)
        {
            if (id == null)
            {
                return Json(new HttpStatusCodeResult(HttpStatusCode.BadRequest));
            }
            Criterion criterion = await _mainContainer.CriterionRepository.FirstOrDefaultAsync(criterionT => criterionT.Id == id);
            if (criterion == null)
            {
                return Json(new HttpStatusCodeResult(HttpStatusCode.InternalServerError));//HttpNotFound());
            }
            criterion.IsDeleted = true;
            _mainContainer.CriterionRepository.Attach(criterion);
            var subCriterions =
                _mainContainer.SubCriterionRepository.Where(subCriterion => subCriterion.Criterion.Id == criterion.Id);

CommitteeAdministration/CommitteeAdministration/Views/Criteria/Create.cshtml
@model CommitteeManagement.Model.Criterion

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Criterion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coefficient, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Coefficient, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Coefficient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDeleted, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDeleted)
                    @Html.ValidationMessageFor(model => model.IsDeleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CommitteeAdministration/CommitteeAdministration/Views/Criteria/CreateCriterionPartial.cshtml
@model CommitteeAdministration.ViewModels.CreateCriterionViewModel

    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
   
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <style>
        .ui-widget-header, .ui-state-default, .ui-button {
            background: #b9cd6d;
            border: 1px solid #b9cd6d;
            color: #FFFFFF;
            font-weight: bold;
        }
    </style>

    <script type="text/javascript">

        $(document).ready(function() {
            console.log("rrrrr");
            ('form').submit(function (e) {
                console.log("inter function");
                e.preventDefault();
                var dd = $("#CriterionSubmitForm").serialize();
                console.log(dd);
                $.ajax({
                    url: "/Criteria/CreateCriterionPartial",
                    type: 'post',
                    dataType: 'json',
                    async: false,
                    data: $("#CriterionSubmitForm").serialize(),
                    success: function (response) {
                        var result = response.StatusCode;
                        if (result === 200) {
                            alert("افزودن معیار با موفقیت انجام شد");
                            $("#CriterionSubmitForm").hide();
                        } else {
                            alert("مشکلی در افزودن پیش آمد. مجددا تلاش کنید.");
                            $("#CriterionSubmitForm").hide();
                        }
                    },
                    error: function (xhr) {

                        alert("Something went wrong, please try again");
                        $("#CriterionSubmitForm").hide();
                    }

                });

            });
            
        })

    </script>


    @using (Html.BeginForm("CreateCriterionPartial", "Criteria", FormMethod.Post, new { @id = "CriterionSubmitForm" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal" dir="rtl" align="right">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                </div>
                @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label", @dir = "rtl", @align = "right" })
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Coefficient, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Coefficient, "", new { @class = "text-danger" })
                </div>
                @Html.LabelFor(model => model.Coefficient, htmlAttributes: new { @class = "control-label", @dir = "rtl", @align = "right" })

            </div>
            <div class="form-group" style="display: none">
                @Html.EditorFor(model => model.Committee)
            </div>
           

        </div>
    }


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CommitteeAdministration/CommitteeAdministration/Views/Criteria/Delete.cshtml
@model CommitteeManagement.Model.Criterion

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Criterion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coefficient)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coefficient)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CommitteeAdministration/CommitteeAdministration/Views/Criteria/Details.cshtml
@model CommitteeManagement.Model.Criterion

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Criterion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Coefficient)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coefficient)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CommitteeAdministration/CommitteeAdministration/Views/Criteria/Edit.cshtml
@model CommitteeManagement.Model.Criterion

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Criterion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coefficient, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Coefficient, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Coefficient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CommitteeAdministration/CommitteeAdministration/Views/Criteria/EditCriterionPartial.cshtml
@using CommitteeManagement.Model
@model CommitteeManagement.Model.Criterion
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<style>
    .ui-widget-header, .ui-state-default, .ui-button {
        background: #b9cd6d;
        border: 1px solid #b9cd6d;
        color: #FFFFFF;
        font-weight: bold;
    }
</style>



@using (Html.BeginForm("EditCriterionPartial", "Criteria", FormMethod.Post, new { @id = "CriterionEditForm" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" align="right" dir="rtl">
        <h4>معیار</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">

            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Subject, "", new {@class = "text-danger"})
            </div>
            @*@Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })*@
            @Html.Label("","عنوان معیار", htmlAttributes: new { @class = "control-label col-md-2" })
        </div>

        <div class="form-group" style="display: none">
            @*@Html.LabelFor(model => model.Coefficient, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.Coefficient, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Coefficient, "", new {@class = "text-danger"})
            </div>
            @Html.Label("", "ضریب معیار", htmlAttributes: new { @class = "control-label col-md-2" })
        </div>

      
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CommitteeAdministration/CommitteeAdministration/Views/Criteria/Index.cshtml
@model IEnumerable<CommitteeManagement.Model.Criterion>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Coefficient)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Where(item => !item.IsDeleted.GetValueOrDefault(false)))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Coefficient)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = item.Id}) |
                @Html.ActionLink("Details", "Details", new {id = item.Id}) |
                @Html.ActionLink("Delete", "Delete", new {id = item.Id})
            </td>
        </tr>
    }

</table>